### ISSUE TITLE
Rewards for nodes calculated wrong

### ISSUE THREAD

**Issue by HyperPeek** [SmartCash/smarthub_local#12]
![Bild_2021-04-01_150051](https://user-images.githubusercontent.com/21068858/113297561-0bf53d00-92fb-11eb-8caf-243eebbb57c3.png)

**Comment by HyperPeek** [comment]
This was with zero funds after just starting the wallet. After receiving some funds the reward is correct, so maybe just a sync issue at startup.

**Comment by HyperPeek** [comment]
I saw this from time to time now and to me it looks like this happens before connection to network is available. Maybe we should just change the reward to "unknown" or some sensible value then.

**Comment by enriquesouza** [comment]
This isn't related to your address but in general
