### ISSUE TITLE
Sent all not updated after entering a chat message

### ISSUE THREAD

**Issue by HyperPeek** [SmartCash/smarthub_local#14]
- Select Send
- fill in address
- Klick "Send All" -> max amount -0.001 is filled in
- Enter a chat message in "Write your message"
- Enter correct pwd
- Hit Send -> will silently fail without error
As the chat message requires an additional fee, this fails.
Suggestion: bring up a message about the additional fee or update the amount after filling a message.

**Comment by brunohenz** [comment]
In the new version, the msg error appear when amount exceded.
