### ISSUE TITLE
Related to #13 - Chat - incorrect pw no error message

### ISSUE THREAD

**Issue by TBO-git** [SmartCash/smarthub_local#23]
Using version 1.0.1-dev
1. Go to Chat
2. Enter a receiving address
3. Enter a message
4. Enter an incorrect password

Expected result:
error message shown

Actual result:
message history reloads, message box and pw remains
no error message is shown

**Comment by brunohenz** [comment]
It's look like you using a old version wallet. i can't reproduce.
