### ISSUE TITLE
Showing "AT INVALID DATE" in chat

### ISSUE THREAD

**Issue by TBO-git** [SmartCash/smarthub_local#24]
How to reproduce:
1. send a chat message and shortly after go to the receiving address
2. Look at the timestamp of the last message
![issue_invalidtimestamp](https://user-images.githubusercontent.com/36732476/113507370-a0ba9d80-957c-11eb-9694-607bc0bc75ea.JPG)

**Comment by brunohenz** [comment]
It's look like you using a old version wallet. i can't reproduce.
