### ISSUE TITLE
Chat refresh does not work correctly

### ISSUE THREAD

**Issue by TBO-git** [SmartCash/smarthub_local#25]
Issue: when sending a chat message, the send message does not appear or takes long time to appear. When clicking refresh or having it auto refresh it still does not show. It is quicker to go to the receiving address and see it there.

How to reproduce:
1. Select a existing chat
2. Enter a new message & pw
3. Click send.
4. Wait 5sec
5. Go to the receiving address
6. See the chat message
7. Enter a new message & pw
8. Click send
9. Wait 5 sec
10. Click refresh

Expected behaviour:
message is visible

Actual behaviour:
message is still not visible

**Comment by brunohenz** [comment]
It's look like you using a old version wallet. i can't reproduce.
