### ISSUE TITLE
Rewards Loader GIF

### ISSUE THREAD

**Issue by enriquesouza** [SmartCash/smarthub_local#29]
Add a loader when loading rewards information in the TAB Rewards. 

It now only appears from nowhere. 

[]`s.
<img width="1117" alt="Screen Shot 2021-04-06 at 12 45 33" src="https://user-images.githubusercontent.com/1700699/113763004-6a913100-96d6-11eb-8243-5774d378f5ad.png">

**Comment by brunohenz** [comment]
Done!
