### ISSUE TITLE
Recommendation/Feature request: Smartreward activation

### ISSUE THREAD

**Issue by TBO-git** [SmartCash/smarthub_local#33]
This is not a bug but a feature request:

To make it more convenient and less manual mistake prone, automate the double sending to same address for smart reward activation. There are different solutions for this.
My recommendation would be to add a button on the smartreward tab with the label "activate this address".
Once pressing the button 2 payments are issued after each other (max amount in the address to itself).
Show a message to the user to confirm that the button was pressed and that the address is being activated, and what the expected time is that the address will be activated.

Expected result after clicking the button:
after pressing the button, the address is activated for smart rewards

**Comment by thesolarminer** [comment]
This is already done.  If you have the latest version under the SmartRewards menu it will show a big ActivateRewards button when you have an address with over 1000 smart in it.  You may need to restart the wallet on a first depost for the button to show.

**Comment by TBO-git** [comment]
Thanks for the clarification!
