### ISSUE TITLE
Main Balance colors

### ISSUE THREAD

**Issue by enriquesouza** [SmartCash/smarthub_local#37]
Right now everything is yellow but the text show be like described bellow:

Balance: (gray) ∑999.9740 (yellow)
Locked: (gray) ∑0.9740 (yellow)

<img width="435" alt="Screen Shot 2021-04-07 at 22 48 12" src="https://user-images.githubusercontent.com/1700699/113970251-d0270f80-97f3-11eb-951e-8eb000d214dd.png">

**Comment by brunohenz** [comment]
Done. I added a space between lines too
